export const YES_NO_OPTIONS = [
  { value: "YES", label: "Yes" },
  { value: "NO", label: "No" },
]

export const GENDER_OPTIONS = [
  { value: "M", label: "Male" },
  { value: "F", label: "Female" },
]
export const GENDER_OPTIONS_UK = [
  { value: "ERKEK", label: "Male" },
  { value: "KADIN", label: "Female" },
]
export const MARITAL_STATUS_OPTIONS = [
  { value: "SINGLE", label: "Single" },
  { value: "MARRIED", label: "Married" },
  { value: "DIVORCED", label: "Divorced" },
  { value: "WIDOWED", label: "Widowed" },
  { value: "SEPARATED", label: "Separated" },
]
export const MARITAL_STATUS_OPTIONS_UK = [
  { value: "BEKAR", label: "Single" },
  { value: "EVLI", label: "Married" },
  { value: "BOSANMIS", label: "Divorced" },
  { value: "DUL", label: "Widowed" },
  { value: "KAYIT DIŞI BİRLİKTELİK", label: "Unregistered Partnership" },
]
export const monthOptions = [
  { value: "JAN", label: "January" },
  { value: "FEB", label: "February" },
  { value: "MAR", label: "March" },
  { value: "APR", label: "April" },
  { value: "MAY", label: "May" },
  { value: "JUN", label: "June" },
  { value: "JUL", label: "July" },
  { value: "AUG", label: "August" },
  { value: "SEP", label: "September" },
  { value: "OCT", label: "October" },
  { value: "NOV", label: "November" },
  { value: "DEC", label: "December" },
]
export const COUNTRY_OPTIONS = [
  { value: "TURKEY", label: "Turkey" },
  { value: "AFGHANISTAN", label: "Afghanistan" },
  { value: "ALBANIA", label: "Albania" },
  { value: "ALGERIA", label: "Algeria" },
  { value: "AMERICAN SAMOA", label: "American Samoa" },
  { value: "ANDORRA", label: "Andorra" },
  { value: "ANGOLA", label: "Angola" },
  { value: "ANGUILLA", label: "Anguilla" },
  { value: "ANTIGUA AND BARBUDA", label: "Antigua and Barbuda" },
  { value: "ARGENTINA", label: "Argentina" },
  { value: "ARMENIA", label: "Armenia" },
  { value: "ARUBA", label: "Aruba" },
  { value: "AT SEA", label: "At Sea" },
  { value: "AUSTRALIA", label: "Australia" },
  { value: "AUSTRIA", label: "Austria" },
  { value: "AZERBAIJAN", label: "Azerbaijan" },

  { value: "BAHAMAS", label: "Bahamas" },
  { value: "BAHRAIN", label: "Bahrain" },
  { value: "BANGLADESH", label: "Bangladesh" },
  { value: "BARBADOS", label: "Barbados" },
  { value: "BELARUS", label: "Belarus" },
  { value: "BELGIUM", label: "Belgium" },
  { value: "BELIZE", label: "Belize" },
  { value: "BENIN", label: "Benin" },
  { value: "BERMUDA", label: "Bermuda" },
  { value: "BHUTAN", label: "Bhutan" },
  { value: "BOLIVIA", label: "Bolivia" },
  { value: "BOSNIA-HERZEGOVINA", label: "Bosnia and Herzegovina" },
  { value: "BOTSWANA", label: "Botswana" },
  { value: "BRAZIL", label: "Brazil" },
  { value: "BRITISH INDIAN OCEAN TERRITORY", label: "British Indian Ocean Territory" },
  { value: "BRUNEI", label: "Brunei" },
  { value: "BULGARIA", label: "Bulgaria" },
  { value: "BURKINA FASO", label: "Burkina Faso" },
  { value: "BURMA", label: "Burma (Myanmar)" },
  { value: "BURUNDI", label: "Burundi" },

  { value: "CAMBODIA", label: "Cambodia" },
  { value: "CAMEROON", label: "Cameroon" },
  { value: "CANADA", label: "Canada" },
  { value: "CABO VERDE", label: "Cabo Verde" },
  { value: "CAYMAN ISLANDS", label: "Cayman Islands" },
  { value: "CENTRAL AFRICAN REPUBLIC", label: "Central African Republic" },
  { value: "CHAD", label: "Chad" },
  { value: "CHILE", label: "Chile" },
  { value: "CHINA", label: "China" },
  { value: "COLOMBIA", label: "Colombia" },
  { value: "COMOROS", label: "Comoros" },
  { value: "CONGO, DEMOCRATIC REPUBLIC OF THE", label: "Congo, Democratic Republic of the" },
  { value: "CONGO, REPUBLIC OF THE", label: "Congo, Republic of the" },
  { value: "COSTA RICA", label: "Costa Rica" },
  { value: "COTE D`IVOIRE", label: "Côte d’Ivoire" },
  { value: "CROATIA", label: "Croatia" },
  { value: "CUBA", label: "Cuba" },
  { value: "CURACAO", label: "Curaçao" },
  { value: "CYPRUS", label: "Cyprus" },
  { value: "CZECH REPUBLIC", label: "Czech Republic" },

  { value: "DENMARK", label: "Denmark" },
  { value: "DJIBOUTI", label: "Djibouti" },
  { value: "DOMINICA", label: "Dominica" },
  { value: "DOMINICAN REPUBLIC", label: "Dominican Republic" },

  { value: "ECUADOR", label: "Ecuador" },
  { value: "EGYPT", label: "Egypt" },
  { value: "EL SALVADOR", label: "El Salvador" },
  { value: "EQUATORIAL GUINEA", label: "Equatorial Guinea" },
  { value: "ERITREA", label: "Eritrea" },
  { value: "ESTONIA", label: "Estonia" },
  { value: "ESWATINI", label: "Eswatini" },
  { value: "ETHIOPIA", label: "Ethiopia" },

  { value: "FINLAND", label: "Finland" },
  { value: "FRANCE", label: "France" },

  { value: "GERMANY", label: "Germany" },
  { value: "GREECE", label: "Greece" },
  { value: "HUNGARY", label: "Hungary" },
  { value: "ICELAND", label: "Iceland" },
  { value: "INDIA", label: "India" },
  { value: "INDONESIA", label: "Indonesia" },
  { value: "IRAN", label: "Iran" },
  { value: "IRAQ", label: "Iraq" },
  { value: "IRELAND", label: "Ireland" },
  { value: "ISRAEL", label: "Israel" },
  { value: "ITALY", label: "Italy" },

  { value: "JAPAN", label: "Japan" },
  { value: "JORDAN", label: "Jordan" },

  { value: "KAZAKHSTAN", label: "Kazakhstan" },
  { value: "KENYA", label: "Kenya" },
  { value: "KOREA, DEMOCRATIC REPUBLIC OF (NORTH)", label: "Korea, North" },
  { value: "KOREA, REPUBLIC OF (SOUTH)", label: "Korea, South" },

  { value: "LATVIA", label: "Latvia" },
  { value: "LITHUANIA", label: "Lithuania" },
  { value: "LUXEMBOURG", label: "Luxembourg" },

  { value: "MEXICO - STATE OF MEXICO", label: "Mexico – State of Mexico" },
  { value: "NETHERLANDS", label: "Netherlands" },
  { value: "NORWAY", label: "Norway" },

  { value: "PAKISTAN", label: "Pakistan" },
  { value: "POLAND", label: "Poland" },
  { value: "PORTUGAL", label: "Portugal" },
  { value: "QATAR", label: "Qatar" },

  { value: "ROMANIA", label: "Romania" },
  { value: "RUSSIA", label: "Russia" },

  { value: "SAUDI ARABIA", label: "Saudi Arabia" },
  { value: "SOUTH AFRICA", label: "South Africa" },
  { value: "SPAIN", label: "Spain" },
  { value: "SWEDEN", label: "Sweden" },
  { value: "SWITZERLAND", label: "Switzerland" },

  { value: "THAILAND", label: "Thailand" },
  { value: "TUNISIA", label: "Tunisia" },

  { value: "UKRAINE", label: "Ukraine" },
  { value: "UNITED KINGDOM", label: "United Kingdom" },
  { value: "UNITED STATES OF AMERICA", label: "United States of America" },

  { value: "VIETNAM", label: "Vietnam" },
  { value: "ZIMBABWE", label: "Zimbabwe" },
]


export const state = [
  { "value": "ALABAMA", "label": "ALABAMA" },
  { "value": "ALASKA", "label": "ALASKA" },
  { "value": "AMERICAN SAMOA", "label": "AMERICAN SAMOA" },
  { "value": "ARIZONA", "label": "ARIZONA" },
  { "value": "ARKANSAS", "label": "ARKANSAS" },
  { "value": "CALIFORNIA", "label": "CALIFORNIA" },
  { "value": "COLORADO", "label": "COLORADO" },
  { "value": "CONNECTICUT", "label": "CONNECTICUT" },
  { "value": "DELAWARE", "label": "DELAWARE" },
  { "value": "DISTRICT OF COLUMBIA", "label": "DISTRICT OF COLUMBIA" },
  { "value": "FLORIDA", "label": "FLORIDA" },
  { "value": "GEORGIA", "label": "GEORGIA" },
  { "value": "GUAM", "label": "GUAM" },
  { "value": "HAWAII", "label": "HAWAII" },
  { "value": "IDAHO", "label": "IDAHO" },
  { "value": "ILLINOIS", "label": "ILLINOIS" },
  { "value": "INDIANA", "label": "INDIANA" },
  { "value": "IOWA", "label": "IOWA" },
  { "value": "KANSAS", "label": "KANSAS" },
  { "value": "KENTUCKY", "label": "KENTUCKY" },
  { "value": "LOUISIANA", "label": "LOUISIANA" },
  { "value": "MAINE", "label": "MAINE" },
  { "value": "MARYLAND", "label": "MARYLAND" },
  { "value": "MASSACHUSETTS", "label": "MASSACHUSETTS" },
  { "value": "MICHIGAN", "label": "MICHIGAN" },
  { "value": "MINNESOTA", "label": "MINNESOTA" },
  { "value": "MISSISSIPPI", "label": "MISSISSIPPI" },
  { "value": "MISSOURI", "label": "MISSOURI" },
  { "value": "MONTANA", "label": "MONTANA" },
  { "value": "NEBRASKA", "label": "NEBRASKA" },
  { "value": "NEVADA", "label": "NEVADA" },
  { "value": "NEW HAMPSHIRE", "label": "NEW HAMPSHIRE" },

  { "value": "NEW JERSEY", "label": "NEW JERSEY" },
  { "value": "NEW MEXICO", "label": "NEW MEXICO" },
  { "value": "NEW YORK", "label": "NEW YORK" },
  { "value": "NORTH CAROLINA", "label": "NORTH CAROLINA" },
  { "value": "NORTH DAKOTA", "label": "NORTH DAKOTA" },
  { "value": "NORTHERN MARIANA ISLANDS", "label": "NORTHERN MARIANA ISLANDS" },
  { "value": "OHIO", "label": "OHIO" },
  { "value": "OKLAHOMA", "label": "OKLAHOMA" },
  { "value": "OREGON", "label": "OREGON" },
  { "value": "PENNSYLVANIA", "label": "PENNSYLVANIA" },
  { "value": "PUERTO RICO", "label": "PUERTO RICO" },
  { "value": "RHODE ISLAND", "label": "RHODE ISLAND" },
  { "value": "SOUTH CAROLINA", "label": "SOUTH CAROLINA" },
  { "value": "SOUTH DAKOTA", "label": "SOUTH DAKOTA" },
  { "value": "TENNESSEE", "label": "TENNESSEE" },
  { "value": "TEXAS", "label": "TEXAS" },
  { "value": "UTAH", "label": "UTAH" },
  { "value": "VERMONT", "label": "VERMONT" },
  { "value": "VIRGIN ISLANDS", "label": "VIRGIN ISLANDS" },
  { "value": "VIRGINIA", "label": "VIRGINIA" },
  { "value": "WASHINGTON", "label": "WASHINGTON" },
  { "value": "WEST VIRGINIA", "label": "WEST VIRGINIA" },
  { "value": "WISCONSIN", "label": "WISCONSIN" },
  { "value": "WYOMING", "label": "WYOMING" }
]

export const languages_option = [
  { value: "TURKISH", label: "Turkish" },
  { value: "ENGLISH", label: "English" },
  { value: "FRENCH", label: "French" },
  { value: "GERMAN", label: "German" },
  { value: "RUSSIAN", label: "Russian" },
  { value: "AZERI", label: "Azeri" },
  { value: "JAPANESE", label: "Japanese" },
  { value: "KOREAN", label: "Korean" },
  { value: "CHINESE", label: "Chinese" },
  { value: "ARABIC", label: "Arabic" },
  { value: "SPANISH", label: "Spanish" },
  { value: "PERSIAN", label: "Persian" },
  { value: "PORTUGUESE", label: "Portuguese" },
  { value: "ITALIAN", label: "Italian" },
  { value: "FLEMEN", label: "Flemish" },
  { value: "DANISH", label: "Danish" },
  { value: "GREEK", label: "Greek" },
  { value: "BULGARIAN", label: "Bulgarian" },
  { value: "ROMANIAN", label: "Romanian" },
  { value: "CZECH", label: "Czech" },
  { value: "ESTONIAN", label: "Estonian" },
  { value: "FINNISH", label: "Finnish" },
  { value: "UKRANIAN", label: "Ukrainian" },
  { value: "HINDI", label: "Hindi" },
  { value: "IRISH", label: "Irish" },
  { value: "SWEDISH", label: "Swedish" },
  { value: "ICELANDIC", label: "Icelandic" },
  { value: "URDU", label: "Urdu" },
]
export const allCountries = [
  {"value":"AFGHANISTAN","label":"Afganistan"},
  {"value":"LAND ISLANDS","label":"Åland Adaları"},
  {"value":"ALBANIA","label":"Arnavutluk"},
  {"value":"ALGERIA","label":"Cezayir"},
  {"value":"AMERICAN SAMOA","label":"Amerikan Samoası"},
  {"value":"ANDORRA","label":"Andorra"},
  {"value":"ANGOLA","label":"Angola"},
  {"value":"ANGUILLA","label":"Anguilla"},
  {"value":"ANTARCTICA","label":"Antarktika"},
  {"value":"ANTIGUA AND BARBUDA","label":"Antigua ve Barbuda"},
  {"value":"ARGENTINA","label":"Arjantin"},
  {"value":"ARMENIA","label":"Ermenistan"},
  {"value":"ARUBA","label":"Aruba"},
  {"value":"AUSTRALIA","label":"Avustralya"},
  {"value":"AUSTRIA","label":"Avusturya"},
  {"value":"AZERBAIJAN","label":"Azerbaycan"},
  {"value":"BAHAMAS","label":"Bahamalar"},
  {"value":"BAHRAIN","label":"Bahreyn"},
  {"value":"BANGLADESH","label":"Bangladeş"},
  {"value":"BARBADOS","label":"Barbados"},
  {"value":"BELARUS","label":"Belarus"},
  {"value":"BELGIUM","label":"Belçika"},
  {"value":"BELIZE","label":"Belize"},
  {"value":"BENIN","label":"Benin"},
  {"value":"BERMUDA","label":"Bermuda"},
  {"value":"BHUTAN","label":"Butan"},
  {"value":"BOLIVIA","label":"Bolivya"},
  {"value":"BOSNIA AND HERZEGOVINA","label":"Bosna-Hersek"},
  {"value":"BOTSWANA","label":"Botsvana"},
  {"value":"BOUVET ISLAND","label":"Bouvet Adası"},
  {"value":"BRAZIL","label":"Brezilya"},
  {"value":"BRITISH INDIAN OCEAN TERRITORY","label":"Britanya Hint Okyanusu Toprakları"},
  {"value":"BRUNEI DARUSSALAM","label":"Brunei"},
  {"value":"BULGARIA","label":"Bulgaristan"},
  {"value":"BURKINA FASO","label":"Burkina Faso"},
  {"value":"BURUNDI","label":"Burundi"},
  {"value":"CAMBODIA","label":"Kamboçya"},
  {"value":"CAMEROON","label":"Kamerun"},
  {"value":"CANADA","label":"Kanada"},
  {"value":"CAPE VERDE","label":"Yeşil Burun Adaları"},
  {"value":"CAYMAN ISLANDS","label":"Cayman Adaları"},
  {"value":"CENTRAL AFRICAN REPUBLIC","label":"Orta Afrika Cumhuriyeti"},
  {"value":"CHAD","label":"Çad"},
  {"value":"CHILE","label":"Şili"},
  {"value":"CHINA","label":"Çin"},
  {"value":"CHRISTMAS ISLAND","label":"Christmas Adası"},
  {"value":"COCOS (KEELING) ISLANDS","label":"Cocos (Keeling) Adaları"},
  {"value":"COLOMBIA","label":"Kolombiya"},
  {"value":"COMOROS","label":"Komorlar"},
  {"value":"CONGO","label":"Kongo"},
  {"value":"CONGO, THE DEMOCRATIC REPUBLIC OF THE","label":"Kongo Demokratik Cumhuriyeti"},
  {"value":"COOK ISLANDS","label":"Cook Adaları"},
  {"value":"COSTA RICA","label":"Kosta Rika"},
  {"value":"COTE D\"IVOIRE","label":"Fildişi Sahili"},
  {"value":"CROATIA","label":"Hırvatistan"},
  {"value":"CUBA","label":"Küba"},
  {"value":"CYPRUS","label":"Kıbrıs"},
  {"value":"CZECH REPUBLIC","label":"Çekya"},
  {"value":"DENMARK","label":"Danimarka"},
  {"value":"DJIBOUTI","label":"Cibuti"},
  {"value":"DOMINICA","label":"Dominika"},
  {"value":"DOMINICAN REPUBLIC","label":"Dominik Cumhuriyeti"},
  {"value":"ECUADOR","label":"Ekvador"},
  {"value":"EGYPT","label":"Mısır"},
  {"value":"EL SALVADOR","label":"El Salvador"},
  {"value":"EQUATORIAL GUINEA","label":"Ekvator Ginesi"},
  {"value":"ERITREA","label":"Eritre"},
  {"value":"ESTONIA","label":"Estonya"},
  {"value":"ETHIOPIA","label":"Etiyopya"},
  {"value":"FALKLAND ISLANDS (MALVINAS)","label":"Falkland Adaları"},
  {"value":"FAROE ISLANDS","label":"Faroe Adaları"},
  {"value":"FIJI","label":"Fiji"},
  {"value":"FINLAND","label":"Finlandiya"},
  {"value":"FRANCE","label":"Fransa"},
  {"value":"FRENCH GUIANA","label":"Fransız Guyanası"},
  {"value":"FRENCH POLYNESIA","label":"Fransız Polinezyası"},
  {"value":"FRENCH SOUTHERN TERRITORIES","label":"Fransız Güney Toprakları"},
  {"value":"GABON","label":"Gabon"},
  {"value":"GAMBIA","label":"Gambiya"},
  {"value":"GEORGIA","label":"Gürcistan"},
  {"value":"GERMANY","label":"Almanya"},
  {"value":"GHANA","label":"Gana"},
  {"value":"GIBRALTAR","label":"Cebelitarık"},
  {"value":"GREECE","label":"Yunanistan"},
  {"value":"GREENLAND","label":"Grönland"},
  {"value":"GRENADA","label":"Grenada"},
  {"value":"GUADELOUPE","label":"Guadeloupe"},
  {"value":"GUAM","label":"Guam"},
  {"value":"GUATEMALA","label":"Guatemala"},
  {"value":"GUERNSEY","label":"Guernsey"},
  {"value":"GUINEA","label":"Gine"},
  {"value":"GUINEA-BISSAU","label":"Gine-Bissau"},
  {"value":"GUYANA","label":"Guyana"},
    {"value":"HAITI","label":"Haiti"},
  {"value":"HEARD ISLAND AND MCDONALD ISLANDS","label":"Heard ve McDonald Adaları"},
  {"value":"HOLY SEE (VATICAN CITY STATE)","label":"Vatikan"},
  {"value":"HONDURAS","label":"Honduras"},
  {"value":"HONG KONG","label":"Hong Kong"},
  {"value":"HUNGARY","label":"Macaristan"},
  {"value":"ICELAND","label":"İzlanda"},
  {"value":"INDIA","label":"Hindistan"},
  {"value":"INDONESIA","label":"Endonezya"},
  {"value":"IRAN, ISLAMIC REPUBLIC OF","label":"İran"},
  {"value":"IRAQ","label":"Irak"},
  {"value":"IRELAND","label":"İrlanda"},
  {"value":"ISLE OF MAN","label":"Man Adası"},
  {"value":"ISRAEL","label":"İsrail"},
  {"value":"ITALY","label":"İtalya"},
  {"value":"JAMAICA","label":"Jamaika"},
  {"value":"JAPAN","label":"Japonya"},
  {"value":"JERSEY","label":"Jersey"},
  {"value":"JORDAN","label":"Ürdün"},
  {"value":"KAZAKHSTAN","label":"Kazakistan"},
  {"value":"KENYA","label":"Kenya"},
  {"value":"KIRIBATI","label":"Kiribati"},
  {"value":"KOREA, DEMOCRATIC PEOPLE\"S REPUBLIC OF","label":"Kuzey Kore"},
  {"value":"KOREA, REPUBLIC OF","label":"Güney Kore"},
  {"value":"KUWAIT","label":"Kuveyt"},
  {"value":"KYRGYZSTAN","label":"Kırgızistan"},
  {"value":"LAO PEOPLE\"S DEMOCRATIC REPUBLIC","label":"Laos"},
  {"value":"LATVIA","label":"Letonya"},
  {"value":"LEBANON","label":"Lübnan"},
  {"value":"LESOTHO","label":"Lesotho"},
  {"value":"LIBERIA","label":"Liberya"},
  {"value":"LIBYAN ARAB JAMAHIRIYA","label":"Libya"},
  {"value":"LIECHTENSTEIN","label":"Lihtenştayn"},
  {"value":"LITHUANIA","label":"Litvanya"},
  {"value":"LUXEMBOURG","label":"Lüksemburg"},
  {"value":"MACAO","label":"Makao"},
  {"value":"MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF","label":"Kuzey Makedonya"},
  {"value":"MADAGASCAR","label":"Madagaskar"},
  {"value":"MALAWI","label":"Malavi"},
  {"value":"MALAYSIA","label":"Malezya"},
  {"value":"MALDIVES","label":"Maldivler"},
  {"value":"MALI","label":"Mali"},
  {"value":"MALTA","label":"Malta"},
  {"value":"MARSHALL ISLANDS","label":"Marshall Adaları"},
  {"value":"MARTINIQUE","label":"Martinik"},
  {"value":"MAURITANIA","label":"Moritanya"},
  {"value":"MAURITIUS","label":"Mauritius"},
  {"value":"MAYOTTE","label":"Mayotte"},
  {"value":"MEXICO","label":"Meksika"},
  {"value":"MICRONESIA, FEDERATED STATES OF","label":"Mikronezya"},
  {"value":"MOLDOVA, REPUBLIC OF","label":"Moldova"},
  {"value":"MONACO","label":"Monako"},
  {"value":"MONGOLIA","label":"Moğolistan"},
  {"value":"MONTENEGRO","label":"Karadağ"},
  {"value":"MONTSERRAT","label":"Montserrat"},
  {"value":"MOROCCO","label":"Fas"},
  {"value":"MOZAMBIQUE","label":"Mozambik"},
  {"value":"MYANMAR","label":"Myanmar"},
  {"value":"NAMIBIA","label":"Namibya"},
  {"value":"NAURU","label":"Nauru"},
  {"value":"NEPAL","label":"Nepal"},
  {"value":"NETHERLANDS","label":"Hollanda"},
  {"value":"NETHERLANDS ANTILLES","label":"Hollanda Antilleri"},
  {"value":"NEW CALEDONIA","label":"Yeni Kaledonya"},
  {"value":"NEW ZEALAND","label":"Yeni Zelanda"},
  {"value":"NICARAGUA","label":"Nikaragua"},
  {"value":"NIGER","label":"Nijer"},
  {"value":"NIGERIA","label":"Nijerya"},
  {"value":"NIUE","label":"Niue"},
  {"value":"NORFOLK ISLAND","label":"Norfolk Adası"},
  {"value":"NORTHERN MARIANA ISLANDS","label":"Kuzey Mariana Adaları"},
  {"value":"NORWAY","label":"Norveç"},
  {"value":"OMAN","label":"Umman"},
  {"value":"PAKISTAN","label":"Pakistan"},
  {"value":"PALAU","label":"Palau"},
  {"value":"PALESTINIAN TERRITORY, OCCUPIED","label":"Filistin"},
  {"value":"PANAMA","label":"Panama"},
  {"value":"PAPUA NEW GUINEA","label":"Papua Yeni Gine"},
  {"value":"PARAGUAY","label":"Paraguay"},
  {"value":"PERU","label":"Peru"},
  {"value":"PHILIPPINES","label":"Filipinler"},
  {"value":"PITCAIRN","label":"Pitcairn"},
  {"value":"POLAND","label":"Polonya"},
  {"value":"PORTUGAL","label":"Portekiz"},
  {"value":"PUERTO RICO","label":"Porto Riko"},
   {"value":"QATAR","label":"Katar"},
  {"value":"REUNION","label":"Reunion"},
  {"value":"ROMANIA","label":"Romanya"},
  {"value":"RUSSIAN FEDERATION","label":"Rusya"},
  {"value":"RWANDA","label":"Ruanda"},
  {"value":"SAINT HELENA","label":"Saint Helena"},
  {"value":"SAINT KITTS AND NEVIS","label":"Saint Kitts ve Nevis"},
  {"value":"SAINT LUCIA","label":"Saint Lucia"},
  {"value":"SAINT PIERRE AND MIQUELON","label":"Saint Pierre ve Miquelon"},
  {"value":"SAINT VINCENT AND THE GRENADINES","label":"Saint Vincent ve Grenadinler"},
  {"value":"SAMOA","label":"Samoa"},
  {"value":"SAN MARINO","label":"San Marino"},
  {"value":"SAO TOME AND PRINCIPE","label":"Sao Tome ve Principe"},
  {"value":"SAUDI ARABIA","label":"Suudi Arabistan"},
  {"value":"SENEGAL","label":"Senegal"},
  {"value":"SERBIA","label":"Sırbistan"},
  {"value":"SEYCHELLES","label":"Seyşeller"},
  {"value":"SIERRA LEONE","label":"Sierra Leone"},
  {"value":"SINGAPORE","label":"Singapur"},
  {"value":"SLOVAKIA","label":"Slovakya"},
  {"value":"SLOVENIA","label":"Slovenya"},
  {"value":"SOLOMON ISLANDS","label":"Solomon Adaları"},
  {"value":"SOMALIA","label":"Somali"},
  {"value":"SOUTH AFRICA","label":"Güney Afrika"},
  {"value":"SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS","label":"Güney Georgia ve Güney Sandwich Adaları"},
  {"value":"SPAIN","label":"İspanya"},
  {"value":"SRI LANKA","label":"Sri Lanka"},
  {"value":"SUDAN","label":"Sudan"},
  {"value":"SURINAME","label":"Surinam"},
  {"value":"SVALBARD AND JAN MAYEN","label":"Svalbard ve Jan Mayen"},
  {"value":"SWAZILAND","label":"Eswatini"},
  {"value":"SWEDEN","label":"İsveç"},
  {"value":"SWITZERLAND","label":"İsviçre"},
  {"value":"SYRIAN ARAB REPUBLIC","label":"Suriye"},
  {"value":"TAIWAN, PROVINCE OF CHINA","label":"Tayvan"},
  {"value":"TAJIKISTAN","label":"Tacikistan"},
  {"value":"TANZANIA, UNITED REPUBLIC OF","label":"Tanzanya"},
  {"value":"THAILAND","label":"Tayland"},
  {"value":"TIMOR-LESTE","label":"Doğu Timor"},
  {"value":"TOGO","label":"Togo"},
  {"value":"TOKELAU","label":"Tokelau"},
  {"value":"TONGA","label":"Tonga"},
  {"value":"TRINIDAD AND TOBAGO","label":"Trinidad ve Tobago"},
  {"value":"TUNISIA","label":"Tunus"},
  {"value":"TURKEY","label":"Türkiye"},
  {"value":"TURKMENISTAN","label":"Türkmenistan"},
  {"value":"TURKS AND CAICOS ISLANDS","label":"Turks ve Caicos Adaları"},
  {"value":"TUVALU","label":"Tuvalu"},
  {"value":"UGANDA","label":"Uganda"},
  {"value":"UKRAINE","label":"Ukrayna"},
  {"value":"UNITED ARAB EMIRATES","label":"Birleşik Arap Emirlikleri"},
  {"value":"UNITED KINGDOM","label":"Birleşik Krallık"},
  {"value":"UNITED STATES","label":"Amerika Birleşik Devletleri"},
  {"value":"UNITED STATES MINOR OUTLYING ISLANDS","label":"ABD Küçük Dış Adaları"},
  {"value":"URUGUAY","label":"Uruguay"},
  {"value":"UZBEKISTAN","label":"Özbekistan"},
  {"value":"VANUATU","label":"Vanuatu"},
  {"value":"VENEZUELA","label":"Venezuela"},
  {"value":"VIET NAM","label":"Vietnam"},
  {"value":"VIRGIN ISLANDS, BRITISH","label":"Britanya Virjin Adaları"},
  {"value":"VIRGIN ISLANDS, U.S.","label":"ABD Virjin Adaları"},
  {"value":"WALLIS AND FUTUNA","label":"Wallis ve Futuna"},
  {"value":"WESTERN SAHARA","label":"Batı Sahra"},
  {"value":"YEMEN","label":"Yemen"},
  {"value":"ZAMBIA","label":"Zambiya"},
  {"value":"ZIMBABWE","label":"Zimbabve"}]

  export const dateList = [

    {"value":"Year(s)","label":"Year(s)"},
    {"value":"Month(s)","label":"Month(s)"},
    {"value":"Week(s)","label":"Week(s)"},
    {"value":"Day(s)","label":"Day(s)"},
    {"value":"Less Than 24 Hours","label":"Less Than 24 Hours"},



  ]

    export const payerList = [

    {"value":"SELF","label":"Self"},
    {"value":"OTHER","label":"Other Person"},
    {"value":"COMPANY","label":"Other Company/Organization"},
  



  ]

      export const visatype = [

    {"value":"TEMP. BUSINESS OR PLEASURE VISITOR (B)","label":"TEMP. BUSINESS OR PLEASURE VISITOR (B)"},
    {"value":"ACADEMIC OR LANGUAGE STUDENT (F)","label":"ACADEMIC OR LANGUAGE STUDENT (F)"},
    {"value":"EXCHANGE VISITOR (J)","label":"EXCHANGE VISITOR (J)"},

  ]
        export const visaselect = [

    {"value":"BUSINESS OR TOURISM (TEMPORARY VISITOR) (B1/B2)","label":"BUSINESS OR TOURISM (TEMPORARY VISITOR) (B1/B2)"},
    {"value":"BUSINESS/CONFERENCE (B1)","label":"BUSINESS/CONFERENCE (B1)"},
    {"value":"TOURISM/MEDICAL TREATMENT (B2)","label":"TOURISM/MEDICAL TREATMENT (B2)"},
    {"value":"STUDENT (F1)","label":"STUDENT (F1)"},
    {"value":"CHILD OF AN F1 (F2)","label":"CHILD OF AN F1 (F2)"},
    {"value":"SPOUSE OF AN F1 (F2)","label":"SPOUSE OF AN F1 (F2)"},
    {"value":"EXCHANGE VISITOR (J1)","label":"EXCHANGE VISITOR (J1)"},
    {"value":"CHILD OF A J1 (J2)","label":"CHILD OF A J1 (J2)"},
    {"value":"SPOUSE OF A J1 (J2)","label":"SPOUSE OF A J1 (J2)"},


  ]

      export const evet_hayir = [

    {"value":"EVET","label":"Yes"},
    {"value":"HAYIR","label":"No"},

  ]

  export const home_owner =[
     {"value":"KENDİSİ","label":"Self"},
    {"value":"KİRA","label":"For Rent"},
    {"value":"DIGER","label":"Other"},
  ]

    export const work_boolean =[
     {"value":"EV_HANIMI","label":"Home Maker"},
    {"value":"OGRENCI","label":"Student"},
    {"value":"CALISIYOR","label":"Worker"},
    {"value":"EMEKLI","label":"Retired"},
    {"value":"CALISMAYAN","label":"Not Employed"},

  ]

  
    export const travel_select =[
   { "value": "AILE ZIYARETI", "label": "Family Visit" },
  { "value": "ARKADAŞ ZIYARETI", "label": "Friend Visit" },
  { "value": "IS", "label": "Business" },
  { "value": "TRANSİT", "label": "Transit" },
  { "value": "TURISTIK", "label": "Tourism" },
  { "value": "AKADEMIK ZIYARET", "label": "Academic Visit" },
  { "value": "KISA SURELI EGITIM", "label": "Short-Term Study" },
  { "value": "SAGLIK", "label": "Medical Treatment" },
  { "value": "EVLILIK", "label": "Marriage" },
  { "value": "DIGER", "label": "Other" }


  ]

  export const other_visited_country=[
  { "value": "HIC", "label": "Never" },
  { "value": "1 KEZ", "label": "Once" },
  { "value": "2 KEZ", "label": "2 Times" },
  { "value": "3 KEZ", "label": "3 Times" },
  { "value": "4 KEZ", "label": "4 Times" },
  { "value": "5 KEZ", "label": "5 Times" },
  { "value": "6 VE UZERI", "label": "6 or More Times" }
]